3:
	grep -zoP '## Main\s*\K[\s\S]*(?=\s*## EndMain)' 3-final.md | wc -w 

2:
	grep -zoP '## Main\s*\K[\s\S]*(?=\s*## EndMain)' 2-ps.md | wc -w 

1:
	grep -zoP '## Main\s*\K[\s\S]*(?=\s*## EndMain)' 1-sop.md | wc -w 

0:
	grep -zoP '## Main\s*\K[\s\S]*(?=\s*## EndMain)' 0.md | wc -w 