2:
	grep -zoP '## Main\s*\K[\s\S]*(?=\s*## EndMain)' 2-personal-achievements.md | wc -w 

1:
	grep -zoP '## Main\s*\K[\s\S]*(?=\s*## EndMain)' 1-sop.md | wc -w 

0:
	grep -zoP '## Main\s*\K[\s\S]*(?=\s*## EndMain)' 0.md | wc -w 


3:
	grep -zoP '## Main\s*\K[\s\S]*(?=\s*## EndMain)' 3-first-full.md | wc -w 

