wc-5:
	cat 5-sketch.md |  wc -w 

wc-4:
	grep -zoP '## Main\s*\K[\s\S]*(?=\s*## EndMain)' 4-part1.md | wc -w 

wc-3:
	grep -zoP '## Main\s*\K[\s\S]*(?=\s*## EndMain)' 3-part2.md | wc -w 

wc-2:
	grep -zoP '## Main\s*\K[\s\S]*(?=\s*## EndMain)' 2-part2.md | wc -w 

wc-1:
	grep -zoP '## Main\s*\K[\s\S]*(?=\s*## EndMain)' 1-part1.md | wc -w 

wc-0:
	grep -zoP '## Main\s*\K[\s\S]*(?=\s*## EndMain)' 0.md | wc -w 
	grep -zoP '### Part 1: Experience and Background\s*\K[\s\S]*(?=\s*### End1)' 0.md | wc -w 
	grep -zoP '### Part 2: Purpose, Goals, and Achievements\s*\K[\s\S]*(?=\s*### End2)' 0.md | wc -w 
